version: "2"

run:
  timeout: 3m
  tests: true

output:
  sort-order:
    - linter
    - severity
    - file
  show-stats: true

issues: {}

linters:
  default: none
  enable:
    # complexity / maintainability
    - gocyclo
    - gocognit
    - maintidx
    - dupl
    - funlen
    # error handling
    - errcheck
    - errorlint
    # correctness
    - staticcheck
    - govet
    - modernize
    - revive
    # unused code detection
    - unparam
    - unused
    # readability / consistency
    - misspell
  disable:
    # too noisy for map/any-heavy CLI parsing
    - forcetypeassert
    # numeric literals in CLI flags and protocol hints
    - mnd
    # enable later after baseline cleanup
    - gosec

  settings:
    revive:
      rules:
        # 代码质量 / 可读性
        - name: empty-lines
        - name: var-declaration
        - name: superfluous-else
        - name: if-return

        # 命名 / 风格
        - name: receiver-naming
        - name: time-naming
        - name: import-shadowing
        - name: redefines-builtin-id
        - name: unnecessary-stmt
        - name: early-return
        - name: enforce-switch-style
        - name: useless-fallthrough
        - name: useless-break
        - name: identical-switch-branches
        - name: identical-switch-conditions
        - name: max-control-nesting
          arguments:
            - 3

        # 错误处理
        - name: error-strings
        - name: error-return
        - name: unexported-return

        # Go 常见坑
        - name: range
        - name: bare-return
        - name: increment-decrement
        - name: blank-imports
        - name: struct-tag
    gocyclo:
      min-complexity: 25
    gocognit:
      min-complexity: 25
    maintidx:
      under: 15
    dupl:
      threshold: 70
    funlen:
      lines: 50
      statements: 40
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - gocognit
          - funlen
          - unparam
      - path: cmd/ob/main\.go
        linters:
          - gocyclo
        text: "newInstallCmd"
      - path: pkg/cli/handler\.go
        linters:
          - gocyclo
        text: "ExecuteCommand"
      - path: pkg/completion/completion\.go
        linters:
          - gocyclo
        text: "CompleteFlagValues"
      - path: pkg/config/install\.go
        linters:
          - gocyclo
        text: "InstallApp"

formatters:
  enable:
    - goimports
